from tkinter import*
screen = Tk()
screen.geometry("1000x1000")
screen.title("My Address Book")
screen.config(background = 'gray16')
title1 = Label(screen, text = "My Address Book", bg = "dim gray", fg = "snow3", font = ("times", 80, "bold"))
title1.place(x = 100, y = 100)
title2 = Label(screen, text = "Name :", bg = "dim gray", fg = "snow3", font = ("times", 19, "bold"))
title2.place(x = 600, y = 300)
title3 = Entry(screen, bd = 5, bg = "dim gray", fg = "snow3", width = 20, font = ("times", 15, "bold"))
title3.place(x = 750, y = 300)
title4 = Label(screen, text = "Address :", bg = "dim gray", fg = "snow3", font = ("times", 19, "bold"))
title4.place(x = 600, y = 400)
title5 = Entry(screen, bd = 5, bg = "dim gray", fg = "snow3", width = 20, font = ("times", 15, "bold"))
title5.place(x = 750, y = 400)
title6 = Label(screen, text = "Mobile :", bg = "dim gray", fg = "snow3", font = ("times", 19, "bold"))
title6.place(x = 600, y = 500)
title7 = Entry(screen, bd = 5, bg = "dim gray", fg = "snow3", width = 20, font = ("times", 15, "bold"))
title7.place(x = 750, y = 500)
title8 = Label(screen, text = "Email :", bg = "dim gray", fg = "snow3", font = ("times", 19, "bold"))
title8.place(x = 600, y = 600)
title9 = Entry(screen, bd = 5, bg = "dim gray", fg = "snow3", width = 20, font = ("times", 15, "bold"))
title9.place(x = 750, y = 600)
title10 = Label(screen, text = "Birthday :", bg = "dim gray", fg = "snow3", font = ("times", 19, "bold"))
title10.place(x = 600, y = 700)
title11 = Entry(screen, bd = 5, bg = "dim gray", fg = "snow3", width = 20, font = ("times", 15, "bold"))
title11.place(x = 750, y = 700)
address_list = Listbox(screen, width = 70, height = 30)
address_list.place(x = 140, y = 300)
screen.mainloop()
